### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by leon1995** [WakaToa/JodelNet#1]
Hi.

Is this repo still maintained? I think the README is not up to date.
Does the code still work?
It seems that `Location` does not exists anymore

**Comment by TipluLeon** [comment]
Figured out by my self.

But when i try to verify an account (already have device id, refresh tken, distinct id, etc) the `read.McsTag` in `AndroidVerification.cs` is always `MCS_LOGIN_RESPONSE_TAG`. Because of that the while(true) never returns an value

line 159:
`if (read.McsTag == MCSToken.MCS_DATA_MESSAGE_STANZA_TAG)` is never true

using `AndroidVerification.VerifyAccountAsync(jodelUser).Wait();` waits infinitely long

**Comment by WakaToa** [comment]
Hello, the repo is not maintained at the moment. I will try to update it once i got time.
